import "server-only";

import type { DataProvider, ObservationQuery, SignalQuery } from "./provider";
import { DemoDataProvider } from "./demo-provider";
import type {
  AnomalyResult,
  CaseDefinition,
  GeographicLevel,
  HealthObservation,
  ObservationMetric,
  TemporalResolution,
} from "@/types/data";
import fixture from "./opendengue-ph.json";

/**
 * Generated by web/scripts/build-opendengue.mjs from the data track's
 * canonical file (data/processed/opendengue/ph_weekly_national_2012_2023.csv,
 * see planning/OPENDENGUE_RECONCILIATION.md). Rows carry their own geography
 * and level, so a future Admin1/Admin2 file can be added without changing
 * this mapping.
 */
interface OpenDengueFixture {
  meta: {
    source: string;
    version: string;
    extract: string;
    filter: string;
    upstreamUrl: string | null;
    citation: string;
    license: string;
    file: string;
    sha256: string;
    reconciliation: string;
    retrievedAt: string;
    recordedAt: string;
    generator: string;
    validated: { rows: number; firstStart: string; lastEnd: string; sum: number; max: number; min: number };
  };
  rows: Array<{
    id: string;
    diseaseId: string;
    geographyId: string;
    geographicLevel: GeographicLevel;
    periodStart: string;
    periodEnd: string;
    resolution: TemporalResolution;
    metric: ObservationMetric;
    caseDefinition: string;
    value: number;
    sourceRecordId: string;
    upstreamSource: string;
  }>;
}

const DATA = fixture as OpenDengueFixture;
export const OPENDENGUE_META = DATA.meta;

function toCaseDefinition(value: string): CaseDefinition {
  switch (value.toLowerCase()) {
    case "total":
      return "total";
    case "confirmed":
      return "confirmed";
    case "probable":
      return "probable";
    case "suspected":
      return "suspected";
    default:
      return "unspecified";
  }
}

const OBSERVATIONS: HealthObservation[] = DATA.rows
  .map(
    (row): HealthObservation => ({
      id: row.id,
      diseaseId: row.diseaseId,
      geographyId: row.geographyId,
      geographicLevel: row.geographicLevel,
      periodStart: row.periodStart,
      periodEnd: row.periodEnd,
      temporalResolution: row.resolution,
      metric: row.metric,
      caseDefinition: toCaseDefinition(row.caseDefinition),
      value: row.value,
      provenance: {
        sourceIds: ["opendengue"],
        method: "ingested",
        pipeline: DATA.meta.generator,
        upstreamId: row.sourceRecordId,
        upstreamUrl: DATA.meta.upstreamUrl ?? "https://opendengue.org/",
        upstreamVersion: `${DATA.meta.version} · ${DATA.meta.extract}`,
        retrievedAt: `${DATA.meta.retrievedAt}T00:00:00Z`,
        recordedAt: `${DATA.meta.recordedAt}T00:00:00Z`,
        isSample: false,
      },
    }),
  )
  .sort(
    (a, b) =>
      a.geographyId.localeCompare(b.geographyId) ||
      a.temporalResolution.localeCompare(b.temporalResolution) ||
      a.periodStart.localeCompare(b.periodStart),
  );

/**
 * Real formal observations (OpenDengue v1.3, national weekly) alongside the demo
 * provider, which still serves signals, LGUs and trends. Server-only: the
 * source JSON must not be bundled for the browser.
 */
export class OpenDengueProvider implements DataProvider {
  private readonly demo = new DemoDataProvider();

  getDiseases() {
    return this.demo.getDiseases();
  }

  getSignals(query?: SignalQuery) {
    return this.demo.getSignals(query);
  }

  async getHealthObservations(
    diseaseId: string,
    geographyId?: string,
    query?: ObservationQuery,
  ): Promise<HealthObservation[]> {
    return OBSERVATIONS.filter(
      (o) =>
        o.diseaseId === diseaseId &&
        (!geographyId || o.geographyId === geographyId) &&
        (!query?.temporalResolution || o.temporalResolution === query.temporalResolution),
    );
  }

  getLgus() {
    return this.demo.getLgus();
  }

  getLguById(id: string) {
    return this.demo.getLguById(id);
  }

  /** Demo LGU series only; no baseline model has been run on the national series. */
  getTrendSeries(geographyId: string) {
    return this.demo.getTrendSeries(geographyId);
  }

  getNeighborSummaries(geographyId: string) {
    return this.demo.getNeighborSummaries(geographyId);
  }

  /** No baseline or anomaly model has been fitted to the formal series yet. */
  async getAnomalyResults(): Promise<AnomalyResult[]> {
    return [];
  }
}

export const dataProvider: DataProvider = new OpenDengueProvider();
